python main_softshape.py --dataset ACSF1 --num_class 10 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Adiac --num_class 37 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset AllGestureWiimoteX --num_class 10 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset AllGestureWiimoteY --num_class 10 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset AllGestureWiimoteZ --num_class 10 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ArrowHead --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset BME --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Beef --num_class 5 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset BeetleFly --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset BirdChicken --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset CBF --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Car --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Chinatown --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ChlorineConcentration --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset CinCECGTorso --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Coffee --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Computers --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset CricketX --num_class 12 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset CricketY --num_class 12 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset CricketZ --num_class 12 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Crop --num_class 24 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset DiatomSizeReduction --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset DistalPhalanxOutlineAgeGroup --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset DistalPhalanxOutlineCorrect --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset DistalPhalanxTW --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset DodgerLoopDay --num_class 7 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset DodgerLoopGame --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset DodgerLoopWeekend --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ECG200 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ECG5000 --num_class 5 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ECGFiveDays --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset EOGHorizontalSignal --num_class 12 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset EOGVerticalSignal --num_class 12 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Earthquakes --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ElectricDevices --num_class 7 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset EthanolLevel --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset FaceAll --num_class 14 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset FaceFour --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset FacesUCR --num_class 14 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset FiftyWords --num_class 50 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Fish --num_class 7 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset FordA --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset FordB --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset FreezerRegularTrain --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset FreezerSmallTrain --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Fungi --num_class 18 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GestureMidAirD1 --num_class 26 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GestureMidAirD2 --num_class 26 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GestureMidAirD3 --num_class 26 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GesturePebbleZ1 --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GesturePebbleZ2 --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GunPoint --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GunPointAgeSpan --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GunPointMaleVersusFemale --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset GunPointOldVersusYoung --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Ham --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset HandOutlines --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Haptics --num_class 5 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Herring --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset HouseTwenty --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset InlineSkate --num_class 7 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset InsectEPGRegularTrain --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset InsectEPGSmallTrain --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset InsectWingbeatSound --num_class 11 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ItalyPowerDemand --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset LargeKitchenAppliances --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Lightning2 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Lightning7 --num_class 7 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Mallat --num_class 8 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Meat --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset MedicalImages --num_class 10 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset MelbournePedestrian --num_class 10 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset MiddlePhalanxOutlineAgeGroup --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset MiddlePhalanxOutlineCorrect --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset MiddlePhalanxTW --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset MixedShapesRegularTrain --num_class 5 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset MixedShapesSmallTrain --num_class 5 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset MoteStrain --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset NonInvasiveFetalECGThorax1 --num_class 42 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset NonInvasiveFetalECGThorax2 --num_class 42 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset OSULeaf --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset OliveOil --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset PLAID --num_class 11 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset PhalangesOutlinesCorrect --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Phoneme --num_class 39 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset PickupGestureWiimoteZ --num_class 10 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset PigAirwayPressure --num_class 52 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset PigArtPressure --num_class 52 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset PigCVP --num_class 52 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Plane --num_class 7 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset PowerCons --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ProximalPhalanxOutlineAgeGroup --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ProximalPhalanxOutlineCorrect --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ProximalPhalanxTW --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset RefrigerationDevices --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Rock --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ScreenType --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SemgHandGenderCh2 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SemgHandMovementCh2 --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SemgHandSubjectCh2 --num_class 5 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ShakeGestureWiimoteZ --num_class 10 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ShapeletSim --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ShapesAll --num_class 60 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SmallKitchenAppliances --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SmoothSubspace --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SonyAIBORobotSurface1 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SonyAIBORobotSurface2 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset StarLightCurves --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Strawberry --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SwedishLeaf --num_class 15 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Symbols --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset SyntheticControl --num_class 6 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ToeSegmentation1 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset ToeSegmentation2 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Trace --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset TwoLeadECG --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset TwoPatterns --num_class 4 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset UMD --num_class 3 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset UWaveGestureLibraryAll --num_class 8 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset UWaveGestureLibraryX --num_class 8 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset UWaveGestureLibraryY --num_class 8 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset UWaveGestureLibraryZ --num_class 8 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Wafer --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Wine --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset WordSynonyms --num_class 25 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Worms --num_class 5 --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset WormsTwoClass --save_csv_name main_softshape_results --cuda cuda:0;
python main_softshape.py --dataset Yoga --save_csv_name main_softshape_results --cuda cuda:0;